Feature/88 parser to support idea file
salesforce/bazel-ls-eclipse pull request #90
Opened 2021-04-12 09:06 UTC by AlexeiShmidman

# Related Issue
- #88 Re-implement aspect file parser to support IDEA format

# Additional Info
- added support of IntelliJ aspect build

2021-04-12 13:38 UTC, PMitrafanau requested changes

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporter.java
> +            //            TimeTracker.start();    //TODO remove time tracker
Delete this line please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporter.java
> +        //        finally {
Delete commented "finally" block please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/util/IntellijAspectPackageInfoLoader.java
> +    public static final String PROPERTY_BUILD_FILE_ARTIFACT_LOCATION = "build_file_artifact_location"; //$NON-NLS-1$
If we don't need these constants elsewhere, make them private please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/util/IntellijAspectPackageInfoLoader.java
> +                    Optional.<JsonObject>ofNullable(jsonObject).filter((JsonObject rootObject) -> isValid(rootObject))
We can use `IntellijAspectPackageInfoLoader::isValid` instead of `(JsonObject rootObject) -> isValid(rootObject)`

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//    @Test
Uncomment this test please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//        IllegalStateException exception = assertThrows(IllegalStateException.class, () -> {
Uncomment this test please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +        assertEquals(0, 0);
Delete this line if we don't need it anymore

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//    @Test
Uncomment this test please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//    @Test
Uncomment this test please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//    @Test
Uncomment this test please

2021-04-12 13:38 UTC, PMitrafanau commented on com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java
> +//    @Test
Uncomment this test please

2021-04-12 22:01 UTC, kkazakevich approved these changes

2021-04-13 07:25 UTC, PMitrafanau approved these changes

2021-04-13 07:33 UTC, merged